import Head from 'next/head'
import Error from '../../../ui-component/error';
import Loader from '../../../ui-component/loader';
import { useState, useEffect } from 'react';
import axios from 'axios';
import { useRouter } from 'next/router'
import styles from '../../../styles/Confirmation.module.css';

export default function Confirmation() {

    const router = useRouter()
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(false);
    const [errorMsg, setErrorMsg] = useState("");
    const [data, setData] = useState({
    })

    const jobfair = {
        title : "IEEE Job Fair 2022"
    }
    const wlc = {
        title : "IEEE Job Fair 2022"
    }

    useEffect(async () => {
        if (router.query.id !== undefined) {
            try {
                const res = await axios.get(`/api/confirmation?id=${router.query.id}&type=${router.query.type}`);
                console.log(res.data)
                setLoading(false);
                setData(res.data)
            }
            catch (err) {
                setError(true)
                setErrorMsg(err.response !== undefined ? err.response.data.error : String(err))
                // setLoading(false);
            }
        }

    }, [router.query.id])

    return (
        <html>
            <Head>
                <title>Job Fair 2022</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <body className={styles.container}>

                <main className={styles.main}>
                    <div className={styles.eventform} >
                        {error ? <Error setError={setError} msg={errorMsg} /> : null}
                        {loading ?
                            <Loader msg="Loading receipt details" /> :
                            <div className={styles.eventform_con}>
                                <div className={styles.eventdetails}>
                                    <p className={styles.eventdetails_dnt}>Event Registration Confirmation</p>
                                    <h3 className={styles.eventdetails_title}>{router.query.type==="jobfair"?jobfair.title:"WIE ILS 2022 - IEEE Kerala Section"}</h3>
                                    <p className={styles.eventdetails_des}>Thank you for registering for the event. A copy of the receipt has been sent to your registered email</p>
                                    {/* <p className="confirm"></p> */}
                                </div>
                                <div className={styles.paymentDetails}>
                                    <p className={styles.paymentDetails_title}>Payment Details</p>
                                    <div className={styles.paymentDetails_grid}>
                                        {data.orderId !== undefined ?
                                            <><p>Order Id</p> <p>{data.orderId}</p></> : null}
                                        {data.txnId !== undefined ?
                                            <><p >Transaction Id</p> <p className={styles.txn}>{data.txnId}</p></> : null}
                                        {data.paymentStatus!== undefined ?
                                            <><p>Payment Status</p> <p className={styles[data.paymentStatus]}>{data.paymentStatus}</p></> : null}
                                        {data.amount !== undefined ?
                                            <><p>Amount</p> <p>{data.amount}</p></> : null}
                                        {data.txnDate !== undefined ?
                                            <><p>Date</p> <p>{new Date(data.txnDate).toLocaleDateString()} {new Date(data.txnDate).toLocaleTimeString()}</p></> : null}

                                    </div>
                                </div>
                                <div className={styles.paymentDetails}>
                                    <p className={styles.paymentDetails_title}>Event Details</p>
                                    <div className={styles.paymentDetails_grid}>
                                        <p>Date and Time</p> <p>12th Mar 2022 11:00 PM IST</p>
                                        <p>Venue</p> <p>Kottayam, Kerala</p>
                                        {/* <p>Amount</p> <p>Rs 10.00</p>
                            <p>Date</p> <p>12th Mar 2022 11:00 PM IST</p> */}

                                    </div>

                                </div>
                            </div>
                        }
                    </div>
                </main>
            </body>

        </html>

    );
}