import FormBackLayout from "../../layouts/FormBackLayout/formBackLayout"
import styles from '../../styles/Pricing.module.css';
import CreateDiscountCodes from "../../components/createDiscountCodes";
import Notification from "../../ui-component/notification";
import Error from "../../ui-component/error";
import moment from "moment";
import axios from 'axios'
import { useState } from "react";
import { useQuery, useQueryClient } from 'react-query'
import { useRouter } from 'next/router';
import Head from "next/head";
import ViewIcon from "../../icons/view";
import EditIcon from "../../icons/edit";
import Loader from "../../ui-component/loader";
import ViewDiscountCodes from "../../components/viewDiscountCodes";

export default function Pricing() {

    const [show, setShow] = useState(false);
    const [edit, setEdit] = useState(false);
    const [showDisDetails, setShowDisDetails] = useState(false);
    const [error, setError] = useState(false);
    const [errorMsg, setErrorMsg] = useState(false);
    const [notificationMsg, setNotificationMsg] = useState(false);
    const [notification, setNotification] = useState(false);
    const [loading, setLoading] = useState(false);
    const [disabled, setDisabled] = useState(false);
    const [discount, setDiscount] = useState({})
    const queryClient = useQueryClient();
    const router = useRouter();
    const formId = router.query.formId


    const getData = async () => {

        try {
            const res = await axios.get(`/api/form/discounts?formId=${formId}`)
            return res;
        }
        catch (err) {
            setError(true)
            setErrorMsg(err.response !== undefined ? err.response.data.error : err)
        }
    }
    const { isLoading, error: isError, data } = useQuery('pricing', getData, { enabled: formId !== undefined ? true : false })


    const handleAddDiscount = async (data) => {
        var arr = data;
        arr.specific = arr.specific.split(',');
        setLoading(true);
        try {
            await axios.post(`/api/form/discounts/create?formId=wlc`, arr)
            setNotification(true);
            setNotificationMsg("Added the discount code");
            queryClient.invalidateQueries("pricing");
            setLoading(false);
            setShow(false);
        }
        catch (err) {
            setError(true);
            setLoading(false);
            setErrorMsg(err.response !== undefined ? err.response.data.error : err)
        }

    }
    const handleUpdateDiscount = async (data) => {
        
        var arr = data;
        arr.specific = arr.specific.split(',');
        setLoading(true);
        try {
            await axios.put(`/api/form/discounts?formId=wlc`, arr)
            setNotification(true);
            setNotificationMsg("Updated the discount code");
            queryClient.invalidateQueries("pricing");
            setLoading(false);
            setEdit(false);
        }
        catch (err) {
            setError(true);
            setLoading(false);
            setErrorMsg(err.response !== undefined ? err.response.data.error : err)
        }
       
    }



    return (
        <FormBackLayout>
            <Head>
                <title>Pricing</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {showDisDetails ? <ViewDiscountCodes data={discount} setModal={setShowDisDetails} /> : null}
            {notification ? <Notification msg={notificationMsg} setNotify={setNotification} /> : null}
            {error ? <Error setError={setError} msg={errorMsg} /> : null}
            {show ? <CreateDiscountCodes handleSubmit={handleAddDiscount} loading={loading} setModal={setShow} /> : null}
            {edit ? <CreateDiscountCodes handleSubmit={handleUpdateDiscount} data={discount} loading={loading} disabled setModal={setEdit} /> : null}
            {isLoading ?
                <div className={styles.loader}>
                    <Loader />
                    <p>Retrieving data</p>
                </div>
                :
                <div className={styles.pricing}>
                    <div className={styles.header}>
                        <h4>Pricing</h4>
                        {/* <button className={styles.responses_button} onClick={() => setShow(true)}>Create discount codes</button> */}
                    </div>

                    {data !== undefined ? <div className={styles.tabel}>
                        <div className={styles.row}>
                            <p>Type</p>
                            <p>Expiry date</p>
                            <p>Action</p>
                        </div>
                        {Object.keys(data.data.pricing).map((val, key) =>
                            val === "default" || val === "earlyBird" ? <div key={key} className={styles.row}>
                                <p>{val}</p>
                                <p>{data.data.pricing[val].expiryDate !== null ? moment(data.data.pricing[val].expiryDate).format("LLLL") : "None"} {val.expiryDate}</p>
                                <div className={styles.buttons}>
                                    <ViewIcon onClick={() => {
                                        setDiscount({
                                            code: val,
                                            specific:data.data.specific[val]!==undefined?data.data.specific[val].toString():"",
                                            ...data.data.pricing[val]
                                        });
                                        setShowDisDetails(true)
                                    }} />
                                    <EditIcon />
                                </div>
                            </div> : "")}

                    </div> : null}
                    <div className={styles.header}>
                        <h4>Discount codes</h4>
                        <button className={styles.responses_button} onClick={() => setShow(true)}>Create discount codes</button>
                    </div>

                    <div className={styles.tabel}>
                        {data !== undefined ? <div className={styles.tabel}>
                            <div className={styles.row}>
                                <p>Type</p>
                                <p>Expiry date</p>
                                <p>Action</p>
                            </div>
                            {Object.keys(data.data.pricing).map((val, key) =>
                                val !== "default" && val !== "earlyBird" ? <div key={key} className={styles.row}>
                                    <p>{val}</p>
                                    <p>{data.data.pricing[val].expiryDate !== null ? moment(data.data.pricing[val].expiryDate).format("LLLL") : "None"} {val.expiryDate}</p>
                                    <div className={styles.buttons}>
                                        <ViewIcon onClick={() => {
                                            setDiscount({
                                                code: val,
                                                specific:data.data.specific[val]!==undefined?data.data.specific[val].toString():"",
                                                ...data.data.pricing[val]
                                            });
                                            setShowDisDetails(true)
                                        }} />
                                        <EditIcon onClick={() => {
                                            setDiscount({
                                                code: val,
                                                specific:data.data.specific[val]!==undefined?data.data.specific[val].toString():"",
                                                ...data.data.pricing[val]
                                            });
                                            setEdit(true)
                                        }} />
                                    </div>


                                </div> : "")}

                        </div> : null}
                    </div>
                </div>}
        </FormBackLayout>
    )
}